version: '3'

services:  
  kafkaoncontainers-tests:
    image: kafkaoncontainers.tests
    container_name: kafkaoncontainers-tests
    env_file:
      - test.env
    build:
      context: .
      dockerfile: Dockerfile_Test
      args:
        - TEST_FOLDER=KafkaOnContainers/Tests
    networks:
      - backend_network

networks:
  backend_network:
    external: true