version: '3.4'

services:
  zookeeper-service:
    image: confluent/zookeeper
    hostname: zookeeper-service
    ports:
      - 2181:2181
    environment:
      zk_id: "1"
    networks:
      - backend_network

networks:
  backend_network:
    external: true