version: '3.4'

services:
  kafka-service:
    image: confluent/kafka
    hostname: kafka-service
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
    networks:
      - backend_network

networks:
  backend_network:
    external: true