version: '3.4'

services:
  zookeeper-service:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-service
    ports:
      - 2181:2181
    environment:      
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend_network

networks:
  backend_network:
    external: true